#!/usr/bin/env bash

# Variables
user=$(whoami)
hostname=$(hostname -s)
distro="OS X $(sw_vers -productVersion)"
kernel=$(uname)
uptime=$(uptime | awk '{print $3, $4}' | sed 's/,//')
shell="$SHELL"
terminal="$TERM"
packages=$(brew list | wc -l | awk '{print $1 }')
cpu=$(sysctl -n machdep.cpu.brand_string)
mem=$(sysctl -n hw.memsize)
ram="$((mem/1073741824)) GB"
disk=$(df | sed -n 2p | awk '{print $5}')

# Art
echo "
                     ,
                  ,##; 
                 ####             User: $user
                ;#\"               Hostname: $hostname
       ,#####;,   ,;#####;,       Distro: $distro
     ######################\"      Kernel: $kernel
    #####################\"        Uptime: $uptime
    #####################         Shell: $shell
    #####################         Terminal: $terminal
    ######################,       Brew Packages: $packages
     #######################      CPU: $cpu
      ####################\"       Memory: $ram
        #################'        Disk: $disk
         \"####\"\"\"\"####\"

"
